# Defender (django-defender)
# https://django-defender.readthedocs.io/en/latest/

DEFENDER_LOGIN_FAILURE_LIMIT = 3
DEFENDER_LOGIN_FAILURE_LIMIT_USERNAME = 3
DEFENDER_LOGIN_FAILURE_LIMIT_IP = 3
DEFENDER_DISABLE_IP_LOCKOUT = False
DEFENDER_DISABLE_USERNAME_LOCKOUT = False
DEFENDER_COOLOFF_TIME = 300  # in seconds
DEFENDER_ACCESS_ATTEMPT_EXPIRATION = 24  # in hours
DEFENDER_LOCKOUT_TEMPLATE = None
DEFENDER_USERNAME_FORM_FIELD = 'username'
DEFENDER_REDIS_URL = 'redis://localhost:6379/1'
DEFENDER_USE_CELERY = False
